### ISSUE TITLE
[FE] Spotify 계정이 없는 유저 로그인 처리

### ISSUE THREAD

**Issue by hyomin1** [lushlife99/MelLearn#96]

**Comment by lushlife99** [comment]
1. Spotify 계정이 없는 유저
2. Spotify 일반 계정
3. Spotify 프리미엄 계정

3가지로 나눠야함

**Comment by hyomin1** [comment]
1) 계정 없을시 스포티파이 로그인 연동에서 스포티파이 회원가입후 홈 이동
2) 일반 계정 유저는 음악재생관련 서비스 이용 불가능
3) 프리미엄 계정 모든 서비스 이용가능
